name: uncw_learn
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.17.0
  firebase_storage: ^11.7.0
  firebase_core: ^2.27.0
  flutter:
    sdk: flutter
  geolocator: ^7.0.3
  google_maps_flutter: ^2.6.0
  firebase_auth: ^4.19.2
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true