// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRe6DU0-UG7tGTv7KzTwWNmt6fjhY-Gws',
    appId: '1:555322530589:web:f272f5cb3f751e48a7dff4',
    messagingSenderId: '555322530589',
    projectId: 'teal-tours-15923',
    authDomain: 'teal-tours-15923.firebaseapp.com',
    storageBucket: 'teal-tours-15923.appspot.com',
    measurementId: 'G-70ZT0MPFR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQgSVjDv1iTyeGwI0LyrjUaZZNi-u-He8',
    appId: '1:555322530589:android:a3ef5e29063db9aba7dff4',
    messagingSenderId: '555322530589',
    projectId: 'teal-tours-15923',
    storageBucket: 'teal-tours-15923.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT4tcr-T1nHxDIz9aaouHf5vicp2Wh2kM',
    appId: '1:555322530589:ios:922784479e68b9cca7dff4',
    messagingSenderId: '555322530589',
    projectId: 'teal-tours-15923',
    storageBucket: 'teal-tours-15923.appspot.com',
    iosBundleId: 'com.example.uncwLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT4tcr-T1nHxDIz9aaouHf5vicp2Wh2kM',
    appId: '1:555322530589:ios:59d9fbea3edaf535a7dff4',
    messagingSenderId: '555322530589',
    projectId: 'teal-tours-15923',
    storageBucket: 'teal-tours-15923.appspot.com',
    iosBundleId: 'com.example.uncwLearn.RunnerTests',
  );
}
